swagger: '2.0'
info: 
  version: '1.0.0'
  title: 'Cliente API'
  description: ' |
  Esta api tem o objetivo de permiti um CRUD de clientes
    [teste com link](https://www.linkedin.com/in/f%C3%A1bio-ivan-49986541/)
  
  '
consumes:
 - application/json
produces:
 - application/json
tags:
  - name: 'Consulta'
  - name: 'Cadastro'
  - name: 'Manutanção'
  - name: 'Exclusão'
  - name: 'API'
#montanto a url
host: localhost
basePath: /fabioivanov/client_api/1.0.0
schemes: 
 - http
 - https
paths:
  /clientes:
    get:
      tags:
        - Consulta
      summary: 'Consulta todos os clientes'
      operationId: consultarTodos
      description: 'Esta operação tem por objetivo consultar todos os cliente cadastrados'
      responses:
        200:
          description: Sucesso ao consultar todos os clientes
          schema:
            $ref: '#/definitions/Clientes'
        400:
          description: Consulta inválida
        401:
          description: Consulta não autorizada
        404:
          description: Página não encontrada
        500:
          description: Erro interno ao tentar realizar a consulta
          
  /cliente:
    post:
      tags: 
        - Cadastro
      summary: Cadastro de um novo cliente 
      operationId: cadastrarCliente
      description: Esta operação tem por objetivo cadastrar um novo cliente
      parameters:
        - in: body
          required: true
          name: cliente
          schema: 
            $ref: '#/definitions/Cliente'
      responses:
        201:
          description: Sucesso ao cadastrar o novo cliente
          schema:
            $ref: '#/definitions/Cliente'
          headers:
            Location:
              type: 'string'
              description: 'URI do cliente alterado'
        400:
          description: Cadastro inválido
        401:
          description: Cadastro não autorizado
        500:
          description: Erro interno ao tentar cadastrar um cliente
          
  /cliente/{id}:
    put:
      tags:
        - Manutanção
      summary: Altera im cliente existente
      operationId: alterarExistente
      description: Esta operação tem por objetivo alterar um cliente existente
      parameters:
        - in: path
          name: id
          type: integer
          format: int32
          required: true
          description: Id do cliente
        - in: body
          name: cliente
          required: true
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        202:
          description: Sucesso ao alterar um cliente
          schema:
            $ref: '#/definitions/Cliente'
          headers:
            Location:
              type: 'string'
              description: 'URI do cliente alterado'
        400:
          description: Alteração inválida
        401:
          description: Alteração não autorizada
        500:
          description: Erro interno ao tentar realizar a auteração
    get:
      tags:
        - Consulta
      summary: Consulta um cliente existente por ID
      operationId: consultaPorId
      description: Essa consulta tem por objetivo retornar um cliente existente pelo seu Id
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Valor do id do cliente
      responses:
        200:
          description: Sucesso ao consultar um cliente por id
          schema:
            $ref: '#/definitions/Cliente'
        400:
          description: Consulta inválida
        401:
          description: Consulta não autorizada
        404:
          description: Nenhum cliente encontrado para esse Id
        500:
          description: Erro interno ao tentar consultar pelo Id
    delete:
      tags:
        - Exclusão
      summary: Excluir cliente existente
      description: Esse endpoint tem por objetivo excluir um cliente existente
      parameters:
        - in: path
          name: id
          type: integer
          format: int32
          required: true
          description: Número do id do cliente a ser excluído
      responses:
        204:
          description: Sucesso ao exlcuuir o cliente
        400:
          description: Exclusão inválida
        401:
          description: Exclusão não autorizada
        500:
          description: Erro interno ao tentar realizar a exclusão
  /cliente/consulta/{sobrenome}:
    get:
      tags:
       - Consulta
      summary: Consulta cliente existente pelo sobrenome
      operationId: ConsultaPorSobrenome
      description: Esta operação tem por objetivo consultar um cliente existente a partir de seu sobrenome
      parameters:
        - in: path
          name: sobrenome
          type: string
          required: true
          description: Sobrenome do cliente
      responses:
        200:
          description: Sucesso ao consultar o cliente pelo seu sobrenome
          schema:
            $ref: '#/definitions/Cliente'
        400:
          description: Consulta inválida
        401:
          description: Consulta não autorizada
        404:
          description: Nenhum cliente encontrado para essa consulta
        500:
          description: Erro interno ao tentar consultar o cliennte pelo sobrenome
  /cliente/{status}/{id}:
    put:
      tags:
        - Manutanção
      summary: Alteração de status por id
      operationId: alterarStatusPorId
      description: Esta operação tem por objetivo alterar o status do cliente pelo seu id
      parameters:
        - in: path
          name: status
          required: true
          type: string
          enum: [ativo, inativo]
          description: Status do cliente
        - in: path
          name: id
          required: true
          type: integer
          format: int32
          description: Valor do id do cliente
      responses:
        202:
          description: Sucesso ao alterar o status do cliente
          schema:
            $ref: '#/definitions/Cliente'
          headers:
            Location:
              type: 'string'
              description: 'URI do cliente alterado'
        400:
          description: Alteração de status inválida
        401:
          description: Alteração de status não autorizada
        404:
          description: Cliente para alteração de status não encontrado
  /readme:
    get:
      tags:
        - API
      summary: Recupera Readme da API
      operationId: readme
      description: Esse endpoitn retorno o readme da API
      responses:
        200:
          description: Sucesso ao recuperar o readme da API
        500:
          description: Erro interno ao tentar recuperar o readme da API

definitions:
  Clientes:
    type: array
    items:
      $ref: '#/definitions/Cliente'
  Cliente:
    type: object
    properties:
      id: 
        type: integer
        format: int32
        description: Identificador do cliente
      nome:
        type: string
        description: Nome do cliente
      sobrenome:
        type: string
        description: Sobrenome do cliente
      iniciais:
        type: string
        description: Iniciais do cliente
        minLength: 2
        maxLength: 5
      dataNascimento:
        type: string
        format: date
        description: Data de nascimento do cliente
      dataAtualizacao:
        type: string
        format: date-time
        description: Data de atualização dos dados do cliente
      status:
        type: boolean
        description: Status ativo ou inativo do cliente
      tipo:
        type: string
        enum: [interno, externo]
      
      
      
      
      
      
      
      
      
      
      
      
      
      