swagger: '2.0'
info: 
  version: '1.0.0'
  title: 'Cliente API'
  description: ' |
  Esta api tem o objetivo de permiti um CRUD de clientes
    [teste com link](https://www.linkedin.com/in/f%C3%A1bio-ivan-49986541/)
  
  '
consumes:
 - application/json
produces:
 - application/json
tags:
  - name: 'Consulta'
  - name: 'Cadastro'
  - name: 'Manutanção'
  - name: 'Exclusão'
  - name: 'API'
#montanto a url
host: localhost
basePath: /fabioivanov/client_api/1.0.0
schemes: 
 - http
 - https
paths:
  /clientes:
    get:
      tags:
        - Consulta
      summary: 'Consulta todos os clientes'
      operationId: consultarTodos
      description: 'Esta operação tem por objetivo consultar todos os cliente cadastrados'
      responses:
        200:
          description: Sucesso ao consultar todos os clientes
          schema:
            $ref: '#/definitions/Clientes'
        400:
          description: Consulta inválida
        401:
          description: Consulta não autorizada
        404:
          description: Página não encontrada
        500:
          description: Erro interno ao tentar realizar a consulta
  /cliente:
    post:
      tags: 
        - Cadastro
      summary: Cadastro de um novo cliente 
      operationId: cadastrarCliente
      description: Esta operação tem por objetivo cadastrar um novo cliente
      parameters:
        - in: body
          required: true
          name: cliente
          schema: 
            $ref: '#/definitions/Cliente'
      responses:
        201:
          description: Sucesso ao cadastrar o novo cliente
        400:
          description: Cadastro inválido
        401:
          description: Cadastro não autorizado
        500:
          description: Erro interno ao tentar cadastrar um cliente
    
definitions:
  Clientes:
    type: array
    items:
      $ref: '#/definitions/Cliente'
  Cliente:
    type: object
    properties:
      id: 
        type: integer
        format: int32
        description: Identificador do cliente
      nome:
        type: string
        description: Nome do cliente
      sobrenome:
        type: string
        description: Sobrenome do cliente
      iniciais:
        type: string
        description: Iniciais do cliente
        minLength: 2
        maxLength: 5
      dataNascimento:
        type: string
        format: date
        description: Data de nascimento do cliente
      dataAtualizacao:
        type: string
        format: date-time
        description: Data de atualização dos dados do cliente
      status:
        type: boolean
        description: Status ativo ou inativo do cliente
      tipo:
        type: string
        enum: [interno, externo]
      
      
      
      
      
      
      
      
      
      
      
      
      
      